FROM erlang:27.3.4

LABEL maintainer="AI&RD Research Group, Department of Information Engineering, University of Pisa"

WORKDIR /app
COPY fedlangpy .

WORKDIR /app/scripts
RUN erlc /app/scripts/run_federation.erl && chmod +x /app/scripts/*.sh

WORKDIR /app
